# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cyz/NIS1336/NIS_2023/NIS1336_2023

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cyz/NIS1336/NIS_2023/NIS1336_2023

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cyz/NIS1336/NIS_2023/NIS1336_2023/CMakeFiles /home/cyz/NIS1336/NIS_2023/NIS1336_2023/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cyz/NIS1336/NIS_2023/NIS1336_2023/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named todo

# Build rule for target.
todo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 todo
.PHONY : todo

# fast build rule for target.
todo/fast:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/build
.PHONY : todo/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/main.cpp.s
.PHONY : main.cpp.s

src/account.o: src/account.cpp.o

.PHONY : src/account.o

# target to build an object file
src/account.cpp.o:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/src/account.cpp.o
.PHONY : src/account.cpp.o

src/account.i: src/account.cpp.i

.PHONY : src/account.i

# target to preprocess a source file
src/account.cpp.i:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/src/account.cpp.i
.PHONY : src/account.cpp.i

src/account.s: src/account.cpp.s

.PHONY : src/account.s

# target to generate assembly for a file
src/account.cpp.s:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/src/account.cpp.s
.PHONY : src/account.cpp.s

src/reminder.o: src/reminder.cpp.o

.PHONY : src/reminder.o

# target to build an object file
src/reminder.cpp.o:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/src/reminder.cpp.o
.PHONY : src/reminder.cpp.o

src/reminder.i: src/reminder.cpp.i

.PHONY : src/reminder.i

# target to preprocess a source file
src/reminder.cpp.i:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/src/reminder.cpp.i
.PHONY : src/reminder.cpp.i

src/reminder.s: src/reminder.cpp.s

.PHONY : src/reminder.s

# target to generate assembly for a file
src/reminder.cpp.s:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/src/reminder.cpp.s
.PHONY : src/reminder.cpp.s

src/task.o: src/task.cpp.o

.PHONY : src/task.o

# target to build an object file
src/task.cpp.o:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/src/task.cpp.o
.PHONY : src/task.cpp.o

src/task.i: src/task.cpp.i

.PHONY : src/task.i

# target to preprocess a source file
src/task.cpp.i:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/src/task.cpp.i
.PHONY : src/task.cpp.i

src/task.s: src/task.cpp.s

.PHONY : src/task.s

# target to generate assembly for a file
src/task.cpp.s:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/src/task.cpp.s
.PHONY : src/task.cpp.s

src/ui.o: src/ui.cpp.o

.PHONY : src/ui.o

# target to build an object file
src/ui.cpp.o:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/src/ui.cpp.o
.PHONY : src/ui.cpp.o

src/ui.i: src/ui.cpp.i

.PHONY : src/ui.i

# target to preprocess a source file
src/ui.cpp.i:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/src/ui.cpp.i
.PHONY : src/ui.cpp.i

src/ui.s: src/ui.cpp.s

.PHONY : src/ui.s

# target to generate assembly for a file
src/ui.cpp.s:
	$(MAKE) -f CMakeFiles/todo.dir/build.make CMakeFiles/todo.dir/src/ui.cpp.s
.PHONY : src/ui.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... todo"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/account.o"
	@echo "... src/account.i"
	@echo "... src/account.s"
	@echo "... src/reminder.o"
	@echo "... src/reminder.i"
	@echo "... src/reminder.s"
	@echo "... src/task.o"
	@echo "... src/task.i"
	@echo "... src/task.s"
	@echo "... src/ui.o"
	@echo "... src/ui.i"
	@echo "... src/ui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

